---
- name: Perform backup using Restic
  hosts: "{{ host }}"
  become: yes
  vars:
    restic_version: "0.12.1"
    backup_dirs:
      - "/data/npm"
      - "/data/dns"
    restic_password: "{{ restic_mdp }}"
    s3_endpoint: "{{ s3_endpoint_var }}"
    s3_access_key: "{{ s3_access_key_var }}"
    s3_secret_key: "{{ s3_secret_key_var }}"

  tasks:
    - name: Ensure restic is installed
      apt:
        name: restic
        state: present
        
    - name: Initialize restic repository
      command: >
        restic init --repo s3:{{ s3_endpoint }}
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ s3_secret_key }}"

    - name: Effectuer une sauvegarde avec Restic
      command: >
        restic -r s3:{{ s3_endpoint }} backup {{ item }}
      with_items: "{{ backup_dirs }}"
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ s3_secret_key }}"
