---
- name: Perform backup using Restic
  hosts: "{{ host }}"
  become: yes
  vars:
    restic_version: "0.12.1"
    backup_dirs:
      - "/data/npm"
      - "/data/dns"
    backup_destination: "/data/backups"
    restic_password: "{{ restic_mdp }}"

  tasks:
    - name: Ensure restic is installed
      apt:
        name: restic
        state: present

    - name: Créer le répertoire de destination pour les sauvegardes
      file:
        path: "{{ backup_destination }}"
        state: directory
        mode: '0755'
        
    - name: Initialize restic repository
      command: restic init --repo "{{ backup_destination }}"
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"

    - name: Effectuer une sauvegarde avec Restic
      command: >
        restic -r {{ backup_destination }} backup {{ item }}
      with_items: "{{ backup_dirs }}"
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
