---
- name: Perform backup using Restic
  hosts: "{{ host }}"
  become: yes

  tasks:
    - name: Ensure restic is installed
      apt:
        name: restic
        state: present

    - name: Perform Restic backup
      command: restic -r /data/backups backup /data/loki
      environment:
        RESTIC_PASSWORD: "your_secure_password"
