---
- name: Playbook pour créer un utilisateur avec des droits sudoers et un mot de passe par défaut
  hosts: "{{ host }}"
  become: yes
  vars:
    username: "{{ user }}"
    is_sudoer: "{{ sudoers }}"
    default_password: "{{ password }}"
    zsh_path: "/bin/zsh"

  tasks:
    - name: Installer Zsh
      package:
        name: zsh
        state: present

    - name: Créer l'utilisateur avec un mot de passe par défaut et Zsh comme shell
      user:
        name: "{{ username }}"
        state: present
        shell: "{{ zsh_path }}"
        password: "{{ default_password | password_hash('sha512') }}"
        update_password: on_create

    - name: Forcer l'utilisateur à changer son mot de passe à la première connexion
      command: chage -d 0 "{{ username }}"

    - name: Ajouter l'utilisateur au groupe sudo (Debian/Ubuntu) ou wheel (RHEL/CentOS) si nécessaire
      when: is_sudoer | bool
      block:
        - name: Assurer que le groupe sudo ou wheel existe
          group:
            name: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            state: present

        - name: Ajouter l'utilisateur au groupe sudo ou wheel
          user:
            name: "{{ username }}"
            groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            append: yes
