---
- name: Playbook pour créer un utilisateur avec des droits sudoers, Zsh et Oh My Zsh
  hosts: "{{ host }}"
  become: yes
  vars:
    username: "{{ user }}"
    is_sudoer: "{{ sudoers }}"
    default_password: "{{ password }}"
    zsh_path: "/bin/zsh"
    user_home: "/home/{{ user }}"
    oh_my_zsh_script: "/tmp/install_ohmyzsh.sh"

  tasks:
    - name: Installer Zsh
      package:
        name: zsh
        state: present

    - name: Créer l'utilisateur avec un mot de passe par défaut et Zsh comme shell
      user:
        name: "{{ username }}"
        state: present
        shell: "{{ zsh_path }}"
        password: "{{ default_password | password_hash('sha512') }}"
        create_home: yes
        update_password: on_create

    - name: Forcer l'utilisateur à changer son mot de passe à la première connexion
      command: chage -d 0 "{{ username }}"

    - name: Télécharger le script d'installation de Oh My Zsh
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ oh_my_zsh_script }}"
        mode: '0755'

    - name: Exécuter le script d'installation de Oh My Zsh
      command: sh "{{ oh_my_zsh_script }}" --unattended
      become: yes
      become_user: "{{ username }}"
      environment:
        USER: "{{ username }}"
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"

    - name: Changer le shell de l'utilisateur à Zsh
      command: chsh -s "{{ zsh_path }}" "{{ username }}"

    - name: Ajouter l'utilisateur au groupe sudo (Debian/Ubuntu) ou wheel (RHEL/CentOS) si nécessaire
      when: is_sudoer | bool
      block:
        - name: Assurer que le groupe sudo ou wheel existe
          group:
            name: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            state: present

        - name: Ajouter l'utilisateur au groupe sudo ou wheel
          user:
            name: "{{ username }}"
            groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            append: yes
