---
- name: Playbook pour créer un utilisateur avec des droits sudoers et un mot de passe par défaut
  hosts: "{{ host }}"
  become: yes
  vars:
    username: "{{ user }}"
    is_sudoer: "{{ sudoers }}"
    default_password: "{{ password }}"

  tasks:
    - name: Créer l'utilisateur avec un mot de passe par défaut
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ default_password | password_hash('sha512') }}"
        update_password: on_create
        password_expire: 1

    - name: Ajouter l'utilisateur au groupe sudo (Debian/Ubuntu) ou wheel (RHEL/CentOS) si nécessaire
      when: is_sudoer | bool
      block:
        - name: Assurer que le groupe sudo ou wheel existe
          group:
            name: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            state: present

        - name: Ajouter l'utilisateur au groupe sudo ou wheel
          user:
            name: "{{ username }}"
            groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
            append: yes

    - name: S'assurer que le fichier sudoers est configuré correctement
      when: is_sudoer | bool
      block:
        - name: Installer sudo si nécessaire
          package:
            name: sudo
            state: present

        - name: Ajouter l'utilisateur dans sudoers
          lineinfile:
            path: /etc/sudoers
            state: present
            regexp: '^%{{ username }} ALL='
            line: '%{{ username }} ALL=(ALL:ALL) ALL'
            validate: 'visudo -cf %s'
