---
- name: Playbook pour installer un logiciel spécifié par l'utilisateur
  hosts: "{{ host }}"
  become: yes

  tasks:
    - name: Installer le logiciel spécifié
      package:
        name: "{{ software_name }}"
        state: present
