---
- name: Configure Debian Backports and Install Cockpit
  hosts: "{{ host }}"
  become: yes

  tasks:
    - name: Read OS release info
      command: cat /etc/os-release
      register: os_release

    - name: Extract VERSION_CODENAME
      set_fact:
        version_codename: "{{ os_release.stdout | regex_search('VERSION_CODENAME=(\\w+)') | regex_replace('VERSION_CODENAME=', '') }}"

    - name: Add backports repository to sources list
      shell: echo "deb http://deb.debian.org/debian {{ version_codename }}-backports main" > /etc/apt/sources.list.d/backports.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install or update Cockpit from backports
      apt:
        name: cockpit
        default_release: "{{ version_codename }}-backports"
        state: present
