---
- name: Install Prometheus Node Exporter
  hosts: "{{ host }}"
  become: yes

  vars:
    node_exporter_version: "1.8.1"  # Définissez la version de Node Exporter à installer

  tasks:
    - name: Ensure necessary packages are installed
      apt:
        name:
          - wget
          - tar
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure necessary packages are installed
      yum:
        name:
          - wget
          - tar
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64

    - name: Symlink Node Exporter binary
      file:
        src: /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        state: link

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /usr/sbin/nologin

    - name: Create systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=default.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
