---
- name: Ping specified host with Discord webhook notification
  hosts: "{{ target_host }}"
  tasks:
    - name: Ping the target host
      ping:
      register: ping_result
      notify: send_discord_notification

  handlers:
    - name: send_discord_notification
      uri:
        url: "https://discord.com/api/webhooks/1216141232989016164/E2w3FJESy4faUoXxo9vd9QyKRH702YgcfgONrwvXp43sLpsNd2hqFoXNHmiu0ojzYzFG"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "content": "Ping task completed for {{ target_host }} with result: {{ ping_result.ping }}"
          }
        status_code: 204
      delegate_to: localhost

    - name: debug_ping_result
      debug:
        var: ping_result
